# P9K setup
ZSH_THEME="powerlevel9k/powerlevel9k"
# DISABLE_AUTO_TITLE=true
P9K_PROMPT_ADD_NEWLINE=true
P9K_MODE=nerdfont-complete

P9K_LEFT_PROMPT_ELEMENTS=(context os_icon dir gitstatus)
P9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time time)

P9K_TIME_FORMAT='%D{%H:%M}'
P9K_TIME_BACKGROUND='234'
P9K_TIME_FOREGROUND='252'

P9K_DIR_SHOW_WRITABLE=true
P9K_DIR_DEFAULT_BACKGROUND='009'
P9K_DIR_DEFAULT_FOREGROUND='234'
P9K_DIR_NOT_WRITABLE_BACKGROUND='009'
P9K_DIR_NOT_WRITABLE_FOREGROUND='234'
P9K_DIR_HOME_BACKGROUND='209'
P9K_DIR_HOME_SUBFOLDER_BACKGROUND='209'
P9K_DIR_SHORTEN_STRATEGY=truncate_from_right
P9K_DIR_SHORTEN_LENGTH=3

P9K_GITSTATUS_HIDE_BRANCH_ICON=true