ZSH_THEME="powerlevel9k/powerlevel9k"
DISABLE_AUTO_TITLE="true"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir node_version vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='002'
POWERLEVEL9K_NODE_VERSION_BACKGROUND='234'
POWERLEVEL9K_TIME_FOREGROUND='252'
POWERLEVEL9K_TIME_BACKGROUND='234'
POWERLEVEL9K_DIR_HOME_BACKGROUND='216'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='216'
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
plugins=(zsh-autosuggestions git)
source $ZSH/oh-my-zsh.sh